# Generated by Django 3.0.5 on 2020-12-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('search_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('sectorsearch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sharePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricedate', models.DateField()),
                ('openprice', models.FloatField()),
                ('closeprice', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillvalues.Company')),
            ],
        ),
    ]
