# Generated by Django 3.0.5 on 2020-12-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillvalues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyprice', models.FloatField()),
                ('buydate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillvalues.Company')),
            ],
        ),
    ]
