# Generated by Django 3.0.5 on 2020-12-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillvalues', '0002_sharechecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
