# Generated by Django 3.0.5 on 2020-12-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillvalues', '0003_auto_20201213_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='priceshortsearch',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
