# Generated by Django 3.0.5 on 2020-12-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillvalues', '0004_company_priceshortsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareWatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchprice', models.FloatField()),
                ('watchdate', models.DateField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillvalues.Company')),
            ],
        ),
    ]
