# Generated by Django 3.0.5 on 2020-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillvalues', '0005_sharewatchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharechecklist',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
