# Generated by Django 3.2.2 on 2021-07-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillvalues', '0007_auto_20210423_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='exchange',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
