# Generated by Django 3.0.5 on 2021-04-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_sell_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datadate', models.DateField()),
                ('coin', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('amount', models.FloatField()),
                ('trade', models.CharField(max_length=200)),
            ],
        ),
    ]
