# Generated by Django 3.0.5 on 2021-04-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_sell_data',
            name='datadate',
            field=models.DateTimeField(),
        ),
    ]
