# Generated by Django 3.0.5 on 2021-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0003_coin_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin_average',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
