# Generated by Django 3.2.2 on 2021-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0004_coin_average_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin_average',
            name='TotalProfit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
