# Generated by Django 3.2.2 on 2021-07-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0005_coin_average_totalprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin_average',
            name='alltime_high',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin_average',
            name='percent_down',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
