# Generated by Django 3.2.2 on 2021-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0007_coin_gecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin_average',
            name='profit_loss',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
