# Generated by Django 3.2.2 on 2021-07-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0008_coin_average_profit_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin_average',
            name='currentprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
