# Generated by Django 3.2.2 on 2021-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0009_coin_average_currentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin_average',
            name='percent_down',
            field=models.CharField(max_length=20),
        ),
    ]
